#server:
#    port: 10010
#
#system:
#    appId: languageapp
#    token: bWlubGlhCg==
#
#spring:
#    profile: dev
#    application:
#        name: miniapp
#
#
#    datasource:
#        testOnBorrow: true
#        validationQuery: "SELECT 1"
##        driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
#        driverClassName: net.sf.log4jdbc.DriverSpy
#        url: jdbc:log4jdbc:mysql://localhost:3306/minlia_m_language_dev_v1?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
##        url: jdbc:log4jdbc:h2:mem:mit_ecommerce_webapp_v1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE #;AUTO_SERVER=TRUE
##        driverClassName: com.mysql.jdbc.Driver   192.168.1.201   net.sf.log4jdbc.DriverSpy
##        url: jdbc:mysql://localhost:3306/iikar_dims_dev?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
#        name:
#        username: root
#        password:
#        # 123123
#
#
#    jpa:
##        database-platform: org.hibernate.dialect.H2Dialect
##        database: H2
#        database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
#        database: MYSQL
#        show_sql: false
#        properties:
#          jadira.usertype.autoRegisterUserTypes: true
#        hibernate:
##            naming:
##                strategy:
#            ddl-auto: update
#
#security.jwt:
#  tokenExpirationTime: 15 # Number of minutes
#  refreshTokenExpTime: 60 # Minutes
#  tokenIssuer: http://minlia.com
#  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
#
##spring.datasource:
##  url: "jdbc:h2:mem:testdb"
##  driverClassName: org.h2.Driver
##  username: sa
##  password: ""
##  data: "classpath*:data.sql"
##spring.jpa:
##  database-platform: org.hibernate.dialect.H2Dialect
##spring.h2.console.enabled: true
#swagger:
#    title: 国际化接口
#    description: 国际化接口
#    version: 2.0
#    contact: cloud@minlia.com
#    path: /api/.*
#
#aliyun:
#    oss:
#        key: LTAIkdMFkDplTUJX
##        accessId: LTAIkdMFkDplTUJX
##        accessKey: VApB4W2D6rqxJVO0WakbB1Zryn3tOQ
##        bucketName: yinxingnetwork
##        backend: oss-cn-shenzhen.aliyuncs.com
#        secret: VApB4W2D6rqxJVO0WakbB1Zryn3tOQ
#        bucket: yinxingnetwork
#        endpoint: oss-cn-shenzhen.aliyuncs.com
#    sms:
#        accessId: LTAIc3r9adaIXwpH
#        accessKey: i86XebUFjiDY7cDQVCFFpPQBOUTcZt
#        endpoint: cn-hangzhou
#        regionId: cn-hangzhou
#        product: Sms
#        domain: sms.aliyuncs.com
#        signName: 测试
##minlia:
##    messages:
##        basename: mini
##        basenames:
##            - validationMessages
#
#
#
#sms:
#    templates:
#        userRegistration: SMS_56155265